name: prm_20220098
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  encrypt: ^5.0.3
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.1.0
  
  image_picker: ^1.0.7
  just_audio: ^0.9.37
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  salomon_bottom_bar: ^3.3.2
  sqflite: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/PRM_20220098.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
